name: DataTrail in Python
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: .devcontainer/requirements.txt
      - name: Install Python dependencies.
        run: pip install -r .devcontainer/requirements.txt
      - name: Build the documentation.
        run: make docs
      - name: Run doctests.
        run: make doctests
